
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ottoalexander
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Alumno NAlumno=null; 
    Alumno NuevoAlumno = new Alumno();
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CarreraActual = new javax.swing.ButtonGroup();
        CarreraNueva = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sex = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        card = new javax.swing.JTextField();
        Info_Alumno = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Info_Alumno1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Iage = new javax.swing.JLabel();
        Iname = new javax.swing.JLabel();
        Isex = new javax.swing.JLabel();
        Icard = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Info2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Info1 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Iname1 = new javax.swing.JLabel();
        Iage1 = new javax.swing.JLabel();
        Isex1 = new javax.swing.JLabel();
        Icard1 = new javax.swing.JLabel();
        IngMecanica = new javax.swing.JRadioButton();
        IngComputacion = new javax.swing.JRadioButton();
        Matematica = new javax.swing.JRadioButton();
        Administracion = new javax.swing.JRadioButton();
        IngIndustrial = new javax.swing.JRadioButton();
        ActualMecanica = new javax.swing.JRadioButton();
        ActualComputacion = new javax.swing.JRadioButton();
        ActualMatematica = new javax.swing.JRadioButton();
        ActualAdministracion = new javax.swing.JRadioButton();
        ActualIndustrial = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel1.setText("Programa de Cambio de Carrera");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setText("Bienvenido al programa de cambio de carrera, este proyecto fue creado únicamente con el fin de agilizar el  ");

        jLabel4.setText("proceso de cambio de carrera de los alumnos de UVG, siga las Instrucciones para comenzar: ");

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));
        jPanel1.setForeground(new java.awt.Color(51, 153, 0));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Información del alumno:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6)
        );

        jPanel2.setBackground(new java.awt.Color(51, 204, 0));
        jPanel2.setForeground(new java.awt.Color(51, 153, 0));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UVG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel5.setText("Ingrese su nombre:");

        jLabel7.setText("Ingrese su edad:");

        jLabel8.setText("Ingrese su carnet:");

        jLabel9.setText("Ingrese su sexo:");

        Info_Alumno.setBackground(new java.awt.Color(51, 204, 0));
        Info_Alumno.setForeground(new java.awt.Color(255, 255, 255));
        Info_Alumno.setText("Guardar Información");
        Info_Alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Info_AlumnoActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 0, 255));
        jPanel3.setForeground(new java.awt.Color(51, 153, 0));

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ingrese su nueva carrera y la actual:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel11.setText("Carrera Actual:");

        jLabel12.setText("Carrera del cambio:");

        Info_Alumno1.setBackground(new java.awt.Color(51, 0, 255));
        Info_Alumno1.setForeground(new java.awt.Color(255, 255, 255));
        Info_Alumno1.setText("Guardar Información");
        Info_Alumno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Info_Alumno1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 204, 51));
        jPanel4.setForeground(new java.awt.Color(51, 153, 0));

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Completa el proceso:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 432, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13))
        );

        Info2.setColumns(20);
        Info2.setRows(5);
        jScrollPane1.setViewportView(Info2);

        Info1.setColumns(20);
        Info1.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        Info1.setRows(5);
        jScrollPane2.setViewportView(Info1);

        jLabel14.setText("Carrera Actual");

        jLabel15.setText("Carrera Nueva");

        Iname1.setText(".");

        Iage1.setText(".");

        Isex1.setText(".");

        Icard1.setText(".");

        CarreraActual.add(IngMecanica);
        IngMecanica.setText("Ing. Mecanica");
        IngMecanica.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CarreraActual.add(IngComputacion);
        IngComputacion.setText("Ing. C. Computacion");
        IngComputacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CarreraActual.add(Matematica);
        Matematica.setText("Matematica");
        Matematica.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CarreraActual.add(Administracion);
        Administracion.setText("Administracion");
        Administracion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Administracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministracionActionPerformed(evt);
            }
        });

        CarreraActual.add(IngIndustrial);
        IngIndustrial.setText("Ing. Industrial");
        IngIndustrial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CarreraNueva.add(ActualMecanica);
        ActualMecanica.setText("Ing. Mecanica");
        ActualMecanica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualMecanicaActionPerformed(evt);
            }
        });

        CarreraNueva.add(ActualComputacion);
        ActualComputacion.setText("Ing. C. Computacion");
        ActualComputacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualComputacionActionPerformed(evt);
            }
        });

        CarreraNueva.add(ActualMatematica);
        ActualMatematica.setText("Matematica");

        CarreraNueva.add(ActualAdministracion);
        ActualAdministracion.setText("Administracion");

        CarreraNueva.add(ActualIndustrial);
        ActualIndustrial.setText("Ing. Industrial");

        jLabel16.setText("Para mas información consultar: http://www.uvg.edu.gt/ ");

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Antes de continuar haz el cuestionario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 0, 0));
        jPanel5.setForeground(new java.awt.Color(51, 153, 0));

        jLabel17.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Información:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(0, 432, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17))
        );

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Descubre una nueva carrera");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(Iname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Icard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Iage)
                .addGap(577, 577, 577)
                .addComponent(Isex))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(ActualIndustrial)
                                .addComponent(ActualAdministracion)
                                .addComponent(ActualMatematica)
                                .addComponent(ActualComputacion)
                                .addComponent(ActualMecanica))
                            .addGap(103, 103, 103)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(IngMecanica)
                                .addComponent(IngComputacion)
                                .addComponent(Matematica)
                                .addComponent(Administracion)
                                .addComponent(IngIndustrial))
                            .addGap(0, 107, Short.MAX_VALUE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Iage1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Icard1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Iname1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(204, 204, 204)
                                .addComponent(Isex1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(Info_Alumno))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(Info_Alumno1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Iname1)
                            .addComponent(Isex1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Icard1)
                        .addGap(8, 8, 8)
                        .addComponent(Iage1)
                        .addGap(26, 26, 26)
                        .addComponent(Info_Alumno))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ActualMecanica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ActualComputacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ActualMatematica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ActualAdministracion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ActualIndustrial))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IngMecanica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IngComputacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Matematica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Administracion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IngIndustrial))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(Info_Alumno1)
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Iage)
                    .addComponent(Isex)
                    .addComponent(Iname))
                .addGap(28, 28, 28)
                .addComponent(Icard)
                .addGap(298, 298, 298))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Info_AlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info_AlumnoActionPerformed
        // TODO add your handling code here:
        String name1 = name.getText();
        String sex1 = sex.getText();
        String age1 = age.getText();
        float age2 = Float.parseFloat(age1);      
        String card1 = card.getText();
        long card2 = Long.parseLong(card1); 
        NuevoAlumno.setNombre(name1);
	NuevoAlumno.setEdad(age2);
	NuevoAlumno.setSexo(sex1);
	NuevoAlumno.setCarnet(card2); 
        Iname1.setText(String.valueOf("Nombre: "+NuevoAlumno.getNombre()));  
        Iage1.setText(String.valueOf("Edad: "+NuevoAlumno.getEdad())); 
        Isex1.setText(String.valueOf("Sexo: "+NuevoAlumno.getSexo()));
        Icard1.setText(String.valueOf("Carnet: "+NuevoAlumno.getCarnet()));
    }//GEN-LAST:event_Info_AlumnoActionPerformed

    private void Info_Alumno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info_Alumno1ActionPerformed
        // TODO add your handling code here:
        
        //ESTO NO SIRVE
        //Ingenieria Mecanica 
        if (ActualComputacion.isSelected() ){
        NuevoAlumno.llenarCarrera("Ingenieria en ciencia de la computación: ",
        "Ciencias de la Vida","Algoritmos y Programación Básica","Pensamiento Cuantitativo",
        "Comunicación efectiva", "Química General","Introducción a la Ingeniería",
        "coaching para la excelencia",
        
        "Programación Orientada a Objetos", "Estadística 1", "Ciudadanía global", "Física 1",
        "Cálculo1", "Algebra Lineal 1",
        
        "Org. De Computadoras y Assembler", "Física 2", "Cálculo 2", 
        "Programación Plataformas Móviles y Juegos", "Algoritmos y Estructuras de Datos",
        "Guatemala en el contexto mundial",
        
        "Física 3", "Matemática Discreta 1", "Retos Ambientales y sostenibilidad", 
        "Ecuaciones Diferenciales 1", "Investigación y Pensamiento Científico", 
        "Programación de Microprocesadores",
        
        "Bases de Datos", "Ingeniería de Software 1", "Gráficaspor computadora", 
        "Interacción Humano Computador", "Diseño de Videojuegos", "Selectivo de Desarrollo Profesional",
        
        "Emprendimiento e Innovación", "Ingeniería de Software 2", "Sistemas y Tecnologías Web",
        "Selectivo de Desarrollo Profesional", "Lógica Matemática", "Programación Avanzada de Videojuegos",
        
        "Inteligencia Artificial", "Minería de Datos", "Selectivo: Ingeniería Financiera o Microeconomia",
        "Análisis y Diseño de Algoritmos", "Sistemas Operativos", "Desarrollo Ágil de negocios tecnológicos",
        
        "Administración de Proyectos de T", "Data Science 1", "Selectivo", "Redes", "Arquitectura Empresarial", 
        "Modelación y Simulación", 
        
        "Diseño e Innovación en Ingeniería 1", "Computación Paralela y DistribuÍda", "Práctica Profesional",
        "Diseño de Lenguajes de Programación", "Selectivo", "Seguridad en Sistemas de Computación",
        
        "Administración y Mantenimiento sistemas", "Seguridad Ofensiva", "Construcción de Compiladores", 
        "Gestion y admon detalentos", "Planeación Estratégica y Operacional", "Diseño e Innovación en Ingeniería 2");
        Info1.setText(String.valueOf(NuevoAlumno.getCarrera()));}
        
        if (ActualMecanica.isSelected()){
        NuevoAlumno.llenarCarrera("ingeniería mecánica: ",
        "Pensamiento cuantitativo", "introducción a la ingeniería mecánica","dibujo mecánico",
        "algoritmos y programación básica", "Química general","ciudadanía global",
        "coachingpara la excelencia",
        
        "cálculo1", "física 1", "manufactura digital", "ciencias dela vida", "estadística 1", 
        "comunicación efectiva",
        
        "Cálculo 2", "Álgebra Lineal 1", "Física 2", "Materiales 1",
        "Soldadura industrial", "Investigación y pensamiento científico",
        
        "guatemala en el contexto mundial", "ecuaciones diferenciales 1", 
        "mecanica 1: estatica", "introduccion a ingenieria electrica", 
        "maquinas herramienta", "retos ambientes y sostenibilidad",
        
        "metodos numéricos en ingenieria mecanica", "termodinamica 1", 
        "mecanica 2: dinamica", "resistencia de materiales 1", "selectivo (formacion general)", 
        "emprendimiento e innovacion", "mecanica de fluidos 1", "termodinamica 2", 
        "resistencia de materiales 2", "materiales 2", "mecanismos", "selectivo (formacion general)",
        
        "mecanica de fluidos 2", "diseño de ingenieria mecanica 1", "transferencia de calor", 
        "introduccion a diseño y manufactura cad cam", "procesos industriales", 
        "economia de empresas",
        
        "máquinas electromecanicas", "vibraciones mecanicas", "motores de combustion interna", 
        "diseño de ingenieria mecanica 2", "sistemas hidraulicos y neumaticos", 
        "curso selectivo (area de ingenieria para el desarrollo)",
        
        "generacion de potencia", "ingenieria economica", "energia renovable (ingenieria mecanica)", 
        "refrigeracion y acondicionamiento de aire", "diseño e innovacion en ingenieria 1", 
        "elementos finitos",
        
        "sistemas de control", "gestion de mantenimiento industrial", "curso selectivo (área profesional)",
        "gestion de proyectos", "diseño e innovacion en ingeniería 2", "practica profesional");
        Info1.setText(String.valueOf(NuevoAlumno.getCarrera()));}
        
         if (ActualMatematica.isSelected()){
        NuevoAlumno.llenarCarrera( "Matematica: ", 
        "pensamiento cuantitativo", "ciencias de la vida", "coaching para la excelencia", 
        "comunicacion efectiva", "algoritmos y programacion basica", "geometria elemental", 
        "quimica general",
        
        "ciudadania global", "estadistica 1", "geometria moderna", "fisica 1", "calculo 1", 
        "programacion orientada a objetos",
        
        "guatemala en el contexto mundial", "algebra lineal 1", "fisica 2", "matematica discreta 1", 
        "calculo 2", "herramientas tecnologicas para matematica",
        
        "retos ambientales y sostenibilidad", "investgacion y pensamiento cientifico", 
        "ecuaciones diferenciales 1", "teoria de conjuntos", "calculo 3", "algebra lineal 2",
        
        "analisis de variabale real 1", "algebra moderna 1", "ecuaciones diferenciales 2",  
        "estadisticas matematica", "estadistica 2", "curso selectivo de desarrollo profesional",
        "emprendimiento e innovacion", "analisis de variable real 2", "algebra moderna 2", 
        "fisica 3", "data mining", "curso selectivo de desarrollo profesional", 
        
        "metodos numericos 1", "algoritmos y estructuras de datos", "seminario 1 de matematica aplicada", 
        "teoria de la medida", "topologia", "investigacion de operaciones",
        
        "modelacion y simulacion", "data science 1", "seminario 2 de matematica aplicada", 
        "teoria de probabilidades", "metodos numericos 2", "administracion financiera"," ",
        
        "geometria diferencial", "analisis de variable compleja", "seminario 3 de matematica aplicada", 
        "analisis funcional", "practica profesional", "trabajo de graduacion", "curso selectivo educacion",
        " ", " ", " ", " ");
        Info1.setText(String.valueOf(NuevoAlumno.getCarrera()));}
        
         if (ActualAdministracion.isSelected()){
        NuevoAlumno.llenarCarrera( "Administracion: ",
        "pensamiento cuantitativo", "algoritmos y programacion basica", "ciencias de la vida", 
        "contabilidad 1", "ciudadania global", "introduccion a la innovacion y los negocios", "ingles",
        "calculo 1", "fisica 1", "estadistica 1", "quimica general", "comunicacion efectiva", 
        "contabilidad 2",
        
        "calculo 2", "fisica 2", "estadistica 2", "guatemala en el contexto mundial", "microeconomia",
        "ecuaciones diferenciales 1", "retos ambientales y sostenibilidad2", 
        "anthropology", "culture and bussiness", "investigacion y pensamiento cientifico 2",
        "macroeconomia", "contabilidad de costos",
       
        "metodos numericos 1", "ingenieria economica", "curso selectivo", "design thinking", 
        "mercadotecnia 1", "investigacion de operaciones", 
        
        "emprendimiento e innovacion", "data mining", "administracion de empresas familiares", 
        "formulacion y evaluacion de proyectos", "practica profesional", "curso selectivo", 
        "administracion financiera", 
        
        "entorno legal de negocios", "gestion de proyectos", "diseño e innovacion en ingenieria 1", 
        "valuacion de activos", "administracion de la cadena de suministro", "comercio internacional", 
        "teoria de inversiones",
        
        "desarrollo agil de negocios", "tecnologicos", "gestion y administracion de talentos", 
        "diseño e innovacion en ingenieria 2", "finanzas corporativas internacionales", 
        "administracion global y geopolitica",  "", "", "", "", "", "", "", "", "", "");
        Info1.setText(String.valueOf(NuevoAlumno.getCarrera()));}

         if (ActualIndustrial.isSelected()){
        NuevoAlumno.llenarCarrera( "Ingeneria Industrial: ",
        "dibujo cad", "pensamiento cuantitativo", "ciencias de la vida", "comunicacion efectiva",  
        "quimica general", "introduccion a la ingenieria civil", "coaching para la excelencia", "ingles",
        "estadistica 1", "algoritmos y programacion basica", "ciudadania global", "fisica 1", "calculo 1", 
        "materiales 1",
        "guatemala en el contexto mundial", "fisica 2", "geologia", "calculo 2", "algebra lineal 1", 
        "modelado de informacion para edificaciones",
        "retos ambientales y sostenibilidad", "selectivo microeconomia o investigacion de operaciones", 
        "mecanica 1 (estatica)", "carpinteria", "ecuaciones diferenciales", "resistencia de materiales 1", 
        "topografia general","mecanica de fluidos 1", "analisis estructural 1", "mecanica de suelos", 
        "curso selectivo (formacion general)", 
        "resistencia de materiales 2", "sig y geodesia", "analisis estructural 2", "cimentaciones", 
        "curso selectivo (formacion general)", "emprendimiento e innovavion", "hidraulica general", 
        "gestion de proyectos", "estructuras de madera", "concreto 1", "estructuras de acero 1", 
        "dispositivos electricos",
        "concreto 2", "estructuras de acero 2", "hidrologia", "ingenieria sanitaria", 
        "dispositivos electromecanicos", "curso selectivo",
        "introduccion a la ingenieria sismo resistente", "diseño de carreteras", "ingenieria economica", 
        "administracion", "energia renovable (ingenieria mecanica)", "diseño e innovacion 1",
        "diseño de obras hidraulicas", "diseño estructural", "diseño de infraestructura vial", 
        "elementos finitos", "eficiencia energetica en edificaciones", "diseño e innovacion 2");
        Info1.setText(String.valueOf(NuevoAlumno.getCarrera()));} 
         
         
         
         
         
         
       //Carrera Nueva FUNCIONA 
       //Ciencias de las computación         
        if (IngMecanica.isSelected()){
        NuevoAlumno.llenarNuevaCarrera("ingeniería mecánica: ",
        "Pensamiento cuantitativo", "introducción a la ingeniería mecánica","dibujo mecánico",
        "algoritmos y programación básica", "Química general","ciudadanía global",
        "coachingpara la excelencia",
        
        "cálculo1", "física 1", "manufactura digital", "ciencias dela vida", "estadística 1", 
        "comunicación efectiva",
        
        "Cálculo 2", "Álgebra Lineal 1", "Física 2", "Materiales 1",
        "Soldadura industrial", "Investigación y pensamiento científico",
        
        "guatemala en el contexto mundial", "ecuaciones diferenciales 1", 
        "mecanica 1: estatica", "introduccion a ingenieria electrica", 
        "maquinas herramienta", "retos ambientes y sostenibilidad",
        
        "metodos numéricos en ingenieria mecanica", "termodinamica 1", 
        "mecanica 2: dinamica", "resistencia de materiales 1", "selectivo (formacion general)", 
        "emprendimiento e innovacion", "mecanica de fluidos 1", "termodinamica 2", 
        "resistencia de materiales 2", "materiales 2", "mecanismos", "selectivo (formacion general)",
        
        "mecanica de fluidos 2", "diseño de ingenieria mecanica 1", "transferencia de calor", 
        "introduccion a diseño y manufactura cad cam", "procesos industriales", 
        "economia de empresas",
        
        "máquinas electromecanicas", "vibraciones mecanicas", "motores de combustion interna", 
        "diseño de ingenieria mecanica 2", "sistemas hidraulicos y neumaticos", 
        "curso selectivo (area de ingenieria para el desarrollo)",
        
        "generacion de potencia", "ingenieria economica", "energia renovable (ingenieria mecanica)", 
        "refrigeracion y acondicionamiento de aire", "diseño e innovacion en ingenieria 1", 
        "elementos finitos",
        
        "sistemas de control", "gestion de mantenimiento industrial", "curso selectivo (área profesional)",
        "gestion de proyectos", "diseño e innovacion en ingeniería 2", "practica profesional");
        Info2.setText(String.valueOf(NuevoAlumno.getNuevaCarrera()));}
        
        if (IngComputacion.isSelected() ){
        NuevoAlumno.llenarCarrera("Ingenieria en ciencia de la computación: ",
        "Ciencias de la Vida","Algoritmos y Programación Básica","Pensamiento Cuantitativo",
        "Comunicación efectiva", "Química General","Introducción a la Ingeniería",
        "coaching para la excelencia",
        
        "Programación Orientada a Objetos", "Estadística 1", "Ciudadanía global", "Física 1",
        "Cálculo1", "Algebra Lineal 1",
        
        "Org. De Computadoras y Assembler", "Física 2", "Cálculo 2", 
        "Programación Plataformas Móviles y Juegos", "Algoritmos y Estructuras de Datos",
        "Guatemala en el contexto mundial",
        
        "Física 3", "Matemática Discreta 1", "Retos Ambientales y sostenibilidad", 
        "Ecuaciones Diferenciales 1", "Investigación y Pensamiento Científico", 
        "Programación de Microprocesadores",
        
        "Bases de Datos", "Ingeniería de Software 1", "Gráficaspor computadora", 
        "Interacción Humano Computador", "Diseño de Videojuegos", "Selectivo de Desarrollo Profesional",
        
        "Emprendimiento e Innovación", "Ingeniería de Software 2", "Sistemas y Tecnologías Web",
        "Selectivo de Desarrollo Profesional", "Lógica Matemática", "Programación Avanzada de Videojuegos",
        
        "Inteligencia Artificial", "Minería de Datos", "Selectivo: Ingeniería Financiera o Microeconomia",
        "Análisis y Diseño de Algoritmos", "Sistemas Operativos", "Desarrollo Ágil de negocios tecnológicos",
        
        "Administración de Proyectos de T", "Data Science 1", "Selectivo", "Redes", "Arquitectura Empresarial", 
        "Modelación y Simulación", 
        
        "Diseño e Innovación en Ingeniería 1", "Computación Paralela y DistribuÍda", "Práctica Profesional",
        "Diseño de Lenguajes de Programación", "Selectivo", "Seguridad en Sistemas de Computación",
        
        "Administración y Mantenimiento sistemas", "Seguridad Ofensiva", "Construcción de Compiladores", 
        "Gestion y admon detalentos", "Planeación Estratégica y Operacional", "Diseño e Innovación en Ingeniería 2");
        Info2.setText(String.valueOf(NuevoAlumno.getCarrera()));}
               
         if (Matematica.isSelected()){
        NuevoAlumno.llenarNuevaCarrera( "Matematica: ", 
        "pensamiento cuantitativo", "ciencias de la vida", "coaching para la excelencia", 
        "comunicacion efectiva", "algoritmos y programacion basica", "geometria elemental", 
        "quimica general",
        
        "ciudadania global", "estadistica 1", "geometria moderna", "fisica 1", "calculo 1", 
        "programacion orientada a objetos",
        
        "guatemala en el contexto mundial", "algebra lineal 1", "fisica 2", "matematica discreta 1", 
        "calculo 2", "herramientas tecnologicas para matematica",
        
        "retos ambientales y sostenibilidad", "investgacion y pensamiento cientifico", 
        "ecuaciones diferenciales 1", "teoria de conjuntos", "calculo 3", "algebra lineal 2",
        
        "analisis de variabale real 1", "algebra moderna 1", "ecuaciones diferenciales 2",  
        "estadisticas matematica", "estadistica 2", "curso selectivo de desarrollo profesional",
        "emprendimiento e innovacion", "analisis de variable real 2", "algebra moderna 2", 
        "fisica 3", "data mining", "curso selectivo de desarrollo profesional", 
        
        "metodos numericos 1", "algoritmos y estructuras de datos", "seminario 1 de matematica aplicada", 
        "teoria de la medida", "topologia", "investigacion de operaciones",
        
        "modelacion y simulacion", "data science 1", "seminario 2 de matematica aplicada", 
        "teoria de probabilidades", "metodos numericos 2", "administracion financiera"," ",
        
        "geometria diferencial", "analisis de variable compleja", "seminario 3 de matematica aplicada", 
        "analisis funcional", "practica profesional", "trabajo de graduacion", "curso selectivo educacion",
        " ", " ", " ", " ");
        Info2.setText(String.valueOf(NuevoAlumno.getNuevaCarrera()));}
         
        if (Administracion.isSelected()){
        NuevoAlumno.llenarNuevaCarrera( "Administracion: ",
        "pensamiento cuantitativo", "algoritmos y programacion basica", "ciencias de la vida", 
        "contabilidad 1", "ciudadania global", "introduccion a la innovacion y los negocios", "ingles",
        "calculo 1", "fisica 1", "estadistica 1", "quimica general", "comunicacion efectiva", 
        "contabilidad 2",
        
        "calculo 2", "fisica 2", "estadistica 2", "guatemala en el contexto mundial", "microeconomia",
        "ecuaciones diferenciales 1", "retos ambientales y sostenibilidad2", 
        "anthropology", "culture and bussiness", "investigacion y pensamiento cientifico 2",
        "macroeconomia", "contabilidad de costos",
       
        "metodos numericos 1", "ingenieria economica", "curso selectivo", "design thinking", 
        "mercadotecnia 1", "investigacion de operaciones", 
        
        "emprendimiento e innovacion", "data mining", "administracion de empresas familiares", 
        "formulacion y evaluacion de proyectos", "practica profesional", "curso selectivo", 
        "administracion financiera", 
        
        "entorno legal de negocios", "gestion de proyectos", "diseño e innovacion en ingenieria 1", 
        "valuacion de activos", "administracion de la cadena de suministro", "comercio internacional", 
        "teoria de inversiones",
        
        "desarrollo agil de negocios", "tecnologicos", "gestion y administracion de talentos", 
        "diseño e innovacion en ingenieria 2", "finanzas corporativas internacionales", 
        "administracion global y geopolitica",  "", "", "", "", "", "", "", "", "", "");
        Info2.setText(String.valueOf(NuevoAlumno.getNuevaCarrera()));}
        
        if (IngIndustrial.isSelected()){
        NuevoAlumno.llenarNuevaCarrera( "Ingeneria Industrial: ",
        "dibujo cad", "pensamiento cuantitativo", "ciencias de la vida", "comunicacion efectiva",  
        "quimica general", "introduccion a la ingenieria civil", "coaching para la excelencia", "ingles",
        "estadistica 1", "algoritmos y programacion basica", "ciudadania global", "fisica 1", "calculo 1", 
        "materiales 1",
        "guatemala en el contexto mundial", "fisica 2", "geologia", "calculo 2", "algebra lineal 1", 
        "modelado de informacion para edificaciones",
        "retos ambientales y sostenibilidad", "selectivo microeconomia o investigacion de operaciones", 
        "mecanica 1 (estatica)", "carpinteria", "ecuaciones diferenciales", "resistencia de materiales 1", 
        "topografia general","mecanica de fluidos 1", "analisis estructural 1", "mecanica de suelos", 
        "curso selectivo (formacion general)", 
        "resistencia de materiales 2", "sig y geodesia", "analisis estructural 2", "cimentaciones", 
        "curso selectivo (formacion general)", "emprendimiento e innovavion", "hidraulica general", 
        "gestion de proyectos", "estructuras de madera", "concreto 1", "estructuras de acero 1", 
        "dispositivos electricos",
        "concreto 2", "estructuras de acero 2", "hidrologia", "ingenieria sanitaria", 
        "dispositivos electromecanicos", "curso selectivo",
        "introduccion a la ingenieria sismo resistente", "diseño de carreteras", "ingenieria economica", 
        "administracion", "energia renovable (ingenieria mecanica)", "diseño e innovacion 1",
        "diseño de obras hidraulicas", "diseño estructural", "diseño de infraestructura vial", 
        "elementos finitos", "eficiencia energetica en edificaciones", "diseño e innovacion 2");
        Info2.setText(String.valueOf(NuevoAlumno.getNuevaCarrera()));} 
        
        
    }//GEN-LAST:event_Info_Alumno1ActionPerformed

    private void AdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdministracionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        Cuestionario quiz = null;
        try {
            quiz = new Cuestionario();
        } catch (UnknownHostException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        quiz.setVisible(true);  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ActualMecanicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualMecanicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActualMecanicaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Cursos quiz = new Cursos();
        quiz.setVisible(true); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ActualComputacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualComputacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActualComputacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ActualAdministracion;
    private javax.swing.JRadioButton ActualComputacion;
    private javax.swing.JRadioButton ActualIndustrial;
    private javax.swing.JRadioButton ActualMatematica;
    private javax.swing.JRadioButton ActualMecanica;
    private javax.swing.JRadioButton Administracion;
    private javax.swing.ButtonGroup CarreraActual;
    private javax.swing.ButtonGroup CarreraNueva;
    private javax.swing.JLabel Iage;
    private javax.swing.JLabel Iage1;
    private javax.swing.JLabel Icard;
    private javax.swing.JLabel Icard1;
    private javax.swing.JLabel Iname;
    private javax.swing.JLabel Iname1;
    private javax.swing.JTextArea Info1;
    private javax.swing.JTextArea Info2;
    private javax.swing.JButton Info_Alumno;
    private javax.swing.JButton Info_Alumno1;
    private javax.swing.JRadioButton IngComputacion;
    private javax.swing.JRadioButton IngIndustrial;
    private javax.swing.JRadioButton IngMecanica;
    private javax.swing.JLabel Isex;
    private javax.swing.JLabel Isex1;
    private javax.swing.JRadioButton Matematica;
    private javax.swing.JTextField age;
    private javax.swing.JTextField card;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField sex;
    // End of variables declaration//GEN-END:variables
}
